// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Find() {
  return window['go']['steam']['Steam']['Find']();
}

export function FindLibraryFolders() {
  return window['go']['steam']['Steam']['FindLibraryFolders']();
}

export function ValidateLibraryPath(arg1) {
  return window['go']['steam']['Steam']['ValidateLibraryPath'](arg1);
}

export function ValidateSteamPath(arg1) {
  return window['go']['steam']['Steam']['ValidateSteamPath'](arg1);
}
