// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Find():Promise<void>;

export function FindLibraryFolders():Promise<void>;

export function ValidateLibraryPath(arg1:string):Promise<boolean>;

export function ValidateSteamPath(arg1:string):Promise<boolean>;
