// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get(arg1) {
  return window['go']['types']['Config']['Get'](arg1);
}

export function Set(arg1, arg2) {
  return window['go']['types']['Config']['Set'](arg1, arg2);
}
