// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseDirectory(arg1) {
  return window['go']['gui']['App']['BrowseDirectory'](arg1);
}

export function GetConfig() {
  return window['go']['gui']['App']['GetConfig']();
}

export function GetConfigValue(arg1) {
  return window['go']['gui']['App']['GetConfigValue'](arg1);
}

export function GetRecommendedMods() {
  return window['go']['gui']['App']['GetRecommendedMods']();
}

export function GetSteam() {
  return window['go']['gui']['App']['GetSteam']();
}

export function GetTSMod(arg1) {
  return window['go']['gui']['App']['GetTSMod'](arg1);
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['gui']['App']['OnSecondInstanceLaunch'](arg1);
}

export function SetConfigValue(arg1, arg2) {
  return window['go']['gui']['App']['SetConfigValue'](arg1, arg2);
}

export function StdLogger() {
  return window['go']['gui']['App']['StdLogger']();
}
