import Head from 'next/head'
import { Inter } from 'next/font/google'
import { globalStyles } from '@/styles/globalStyles'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main
        className={inter.className}
        style={globalStyles.main}
      >
        <div style={globalStyles.description}>
          <p>
            Something went horribly wrong. Please{' '}
            <a href="/report-bug">report this</a> as a bug to the developers,
            and include the following information:
          </p>
          <p>... no additional information available ...</p>
        </div>
      </main>
    </>
  )
}
